name: Higher tests

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.02.0
          - 4.03.0
          - 4.05.0
          - 4.07.0
          - 4.09.0
          - 4.11.1


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Deps
        run: opam pin add -n higher .

      - name: Build
        run: opam install higher

